CREATE TABLE `t_touch_task_detail` (
  `id` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `creator` varchar(32) NOT NULL COMMENT '创建人',
  `editor` varchar(32) NOT NULL COMMENT '辑人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '编辑时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除 (0.未删除 1.删除)',
  `task_id` bigint(32) NOT NULL COMMENT '触达任务id',
  `batch_id` varchar(50) NOT NULL COMMENT '分批id',
  `status` tinyint(4) NOT NULL COMMENT '状态：1、待发送，2、发送中，3、发送成功，4、发送失败',
  `shop_id` varchar(32) DEFAULT NULL COMMENT '门店id',
  `linker_id` varchar(32) DEFAULT NULL COMMENT '联系人id',
  `strategy_result` bigint(32) DEFAULT NULL COMMENT '算法策略结果',
  `admin_chat_id` bigint(32) DEFAULT NULL COMMENT '小二企微id',
  `shop_chat_id` bigint(32) DEFAULT NULL COMMENT '门店企微/微信id',
  `content_type` tinyint(4) DEFAULT NULL COMMENT '发送内容类型 1、文本，2、图片-自动抓取主图，3、图片-上传单图，4、文件，5、视频',
  `content` text NOT NULL COMMENT '发送内容',
  `file_name` varchar(200) COMMENT '文件名',
  `fail_type` tinyint(4) DEFAULT NULL COMMENT '失败类型，根据失败内容，映射成对应的type，页面展示默认用这个类型对应的描述覆盖失败原因',
  `fail_reason` varchar(1000) DEFAULT NULL COMMENT '失败原因，保存涂色元信息',
  `fail_time` datetime COMMENT '失败时间',
  `tuse_opt_ser_no` VARCHAR(200) COMMENT '涂色操作编号',
  `tuse_msg_time` datetime COMMENT '涂色消息发送时间',
  `tuse_msg_num` tinyint(4) COMMENT '涂色消息发送编号',
  `task_level` tinyint(4) COMMENT '任务优先级',
  `second_push` tinyint(1) DEFAULT 0 COMMENT '是否二次推送',
  `start_time` datetime COMMENT '任务开始执行的时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='触达任务明细';