CREATE TABLE `sync_ads_crm_a2_subject_d` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `creator` varchar(32) NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `editor` varchar(32) NOT NULL COMMENT '修改人',
  `edit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '编辑时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `dayid` varchar(8) NOT NULL COMMENT '数仓表区块标示',
  `subject_id` bigint(20) COMMENT '项目id',
  `subject_name` varchar(200) COMMENT '项目名',
  `subject_desc` varchar(200) COMMENT '项目描述',
  `subject_status` tinyint(4) COMMENT '项目状态，0待发布 1进行中 2已结束 3已终止',
  `subject_type` varchar(200) COMMENT '项目类型 新签/复购',
  `subject_month` varchar(20) COMMENT '项目月份',
  `subject_start_time` varchar(50) COMMENT '项目开始时间',
  `subject_end_time` varchar(50) COMMENT '项目结束时间',
  `shop_count` int(11) COMMENT '机会门店数',
  `visit_shop_count` int(11) COMMENT '覆盖门店数',
  `valid_visit_shop_count` int(11) COMMENT '有效覆盖门店数',
  `order_shop_count` int(11) COMMENT '转化门店数',
  `hpc_quality_shop_count` int(11) COMMENT 'HPC优质门店数',
  PRIMARY KEY (`id`),
  KEY `idx_subject_month` (`subject_month`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='a2项目统计回流表';

CREATE TABLE `sync_ads_crm_a2_subject_shop_base_d` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `creator` varchar(32) NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `editor` varchar(32) NOT NULL COMMENT '修改人',
  `edit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '编辑时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `dayid` varchar(8) NOT NULL COMMENT '数仓表区块标示',
  `subject_id` bigint(20) COMMENT '项目id',
  `subject_type` varchar(200) COMMENT '项目类型 新签/复购',
  `subject_month` varchar(20) COMMENT '项目月份',
  `shop_id` varchar(200) COMMENT '门店id',
  `shop_code` varchar(200) COMMENT '门店编码',
  `shop_name` varchar(200) COMMENT '门店名',
  `province_id` bigint(32) COMMENT '省id',
  `province_name` varchar(200) COMMENT '省名',
  `city_id` bigint(32) COMMENT '市id',
  `city_name` varchar(200) COMMENT '市名',
  `area_id` bigint(32) COMMENT '区id',
  `area_name` varchar(200) COMMENT '区名',
  `street_id` bigint(32) COMMENT '街道id',
  `street_name` varchar(200) COMMENT '街道名',
  `sale_id` varchar(200) COMMENT '关联销售id',
  `sale_name` varchar(200) COMMENT '关联销售名',
  `sale_user_id` bigint(200) COMMENT '关联销售的user_id',
  `has_visit` tinyint(4) COMMENT '是否存在拜访（覆盖）0否 1是',
  `has_valid_visit` tinyint(4) COMMENT '是否存在有效拜访（有效覆盖）0否 1是',
  `has_order` tinyint(4) COMMENT '是否下单（转化）0否 1是',
  `offtake` int(11) COMMENT '下单罐数，下单罐数统计为 imf_offtake 口径',
  PRIMARY KEY (`id`),
  KEY `idx_subject_month` (`subject_month`),
  KEY `idx_subject_id` (`subject_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='a2项目统计回流表';