CREATE TABLE if not exists dw_salary_sign_rule_public_mid_v2_d
(
    order_id                        string,
    trade_no                        string,
    business_unit                   string COMMENT '业务域',
    category_id_first               bigint COMMENT '商品一级类目id',
    category_id_second              bigint COMMENT '商品二级类目id',
    category_id_first_name          string COMMENT '商品一级类目',
    category_id_second_name         string COMMENT '商品二级类目',
    brand_id                        bigint COMMENT '商品品牌id',
    brand_name                      string COMMENT '商品品牌',
    item_id                         bigint COMMENT '商品ID',
    item_name                       string COMMENT '商品名称',
    item_style                      tinyint COMMENT 'AB类型',
    item_style_name                 string COMMENT 'AB类型名称',
    is_sp_shop                      string COMMENT '是否服务商订单',
    is_bigbd_shop                   string COMMENT '是否大BD门店',
    is_spec_order                   string COMMENT '是否特殊订单',
    shop_item_sign_day              string COMMENT '该门店首次下单该商品日期',
    shop_item_sign_time             string COMMENT '该门店首次下单该商品时间',
    shop_brand_sign_day             string COMMENT '该门店首次下单该品牌日期',
    shop_brand_sign_time            string COMMENT '该门店首次下单该品牌时间',
    pay_time                        string COMMENT '支付时间',
    pay_day                         string COMMENT '支付日期',
    shop_id                         string COMMENT '门店ID',
    shop_name                       string COMMENT '门店名称',
    store_type                      string COMMENT '门店类型',
    store_type_name                 string COMMENT '门店类型名称',
    war_zone_id                     string COMMENT '战区经理ID',
    war_zone_name                   string COMMENT '战区经理',
    war_zone_dep_id                 string COMMENT '战区ID',
    war_zone_dep_name               string COMMENT '战区',
    area_manager_id                 string COMMENT '大区经理id',
    area_manager_name               string COMMENT '大区经理',
    area_manager_dep_id             string COMMENT '大区区域ID',
    area_manager_dep_name           string COMMENT '大区',
    bd_manager_id                   string COMMENT '主管id',
    bd_manager_name                 string COMMENT '主管',
    bd_manager_dep_id               string COMMENT '主管区域ID',
    bd_manager_dep_name             string COMMENT '区域',
    service_user_id_freezed         string COMMENT '冻结销售人员ID',
    service_department_id_freezed   string COMMENT '冻结销售人员部门ID',
    service_user_name_freezed       string COMMENT '冻结销售人员姓名',
    service_feature_name_freezed    string COMMENT '冻结销售人员职能',
    service_job_name_freezed        string COMMENT '冻结销售人员角色',
    service_department_name_freezed string COMMENT '冻结销售人员部门',
    gmv_less_refund                 decimal(18, 2) COMMENT '实货gmv-退款',
    pay_amount                      decimal(18, 2) COMMENT '实货支付金额',
    pay_amount_less_refund          decimal(18, 2) COMMENT '实货支付金额-退款',
    gmv                             decimal(18, 2) COMMENT '实货gmv',
    refund_actual_amount            decimal(18, 2) COMMENT '实货退款',
    refund_retreat_amount           decimal(18, 2) COMMENT '实货清退金额',
    sale_team_name                  string comment '销售团队标识 1:电销部 2:BD部 3:大客户部 4:服务商部 5:美妆销售团队',
    sale_team_freezed_name          string comment '冻结销售团队标识 1:电销部 2:BD部 3:大客户部 4:服务商部 5:美妆销售团队',
    sale_team_id                    int comment '销售团队标识ID',
    sale_team_freezed_id            int comment '冻结销售团队标识ID'
) COMMENT 'sign规则通用方案中间表'
    PARTITIONED BY (dayid string)
    row format delimited fields terminated by '\001'
    stored as orc;