
CREATE TABLE `t_sp_info` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '服务商id',
  `sp_name` varchar(100) NOT NULL COMMENT '服务商名称',
  `company_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `seller_id` varchar(200) DEFAULT NULL COMMENT '供应商id',
  `sp_type` tinyint(2) NOT NULL DEFAULT '1' COMMENT '服务商类型 1:企业  2:个人',
  `linker_name` varchar(30) DEFAULT NULL COMMENT '联系人',
  `linker_phone` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `linker_address` varchar(100) DEFAULT NULL COMMENT '联系地址',
  `pay_account_name` varchar(45) DEFAULT NULL COMMENT '收款账户名称',
  `pay_account_no` varchar(45) DEFAULT NULL COMMENT '收款账号',
  `employee_num` int(11) DEFAULT NULL COMMENT '员工人数',
  `sales_num` int(11) DEFAULT NULL COMMENT '业务员数量',
  `shop_num` int(11) DEFAULT NULL COMMENT '覆盖门店数',
  `annual_sales` varchar(45) DEFAULT NULL COMMENT '年销售额',
  `agent_brand` varchar(200) DEFAULT NULL COMMENT '现代理品牌',
  `referee_person` varchar(45) DEFAULT NULL COMMENT '推荐人',
  `referee_phone` varchar(20) DEFAULT NULL COMMENT '推荐人联系电话',
  `operator_id` varchar(32) DEFAULT NULL COMMENT '运营人员id',
  `settle_type` tinyint(4) DEFAULT '1' COMMENT '结算方式 1.invoice 开票，2.voicegu 天堂声谷',
  `account_voicegu` varchar(32) DEFAULT '' COMMENT '天堂声谷账号',
  `account_voicegu_name` varchar(40) DEFAULT NULL COMMENT '天堂声谷账号姓名',
  `sp_status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '服务商状态:  1 合作中  2 停止合作\n',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `edit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `creator` varchar(45) DEFAULT NULL,
  `editor` varchar(45) DEFAULT NULL,
  `is_deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '删除标记',
  `deposit` int(11) DEFAULT '0' COMMENT '保证金',
  PRIMARY KEY (`id`),
  KEY `idx_sp_name` (`sp_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1866 DEFAULT CHARSET=utf8mb4 COMMENT='服务商信息表';

