insert overwrite table dwd_sp_order_snapshot_d partition (dayid='$v_date')
select
            id,
                sp_id,
                sp_name,
                sp_company_name,
                sp_area_id,
                sp_area_brand_id,
                brand_type,
                sp_shop_server,
                sp_sale_user_id,
                sp_sale_user_name,
                sp_rebate_setting,
                added,
                rebate,
                order_id,
                trade_id,
                trade_no,
                order_time,
                brand_id,
                group_id,
                item_id,
                item_name,
                first_cate_id,
                first_cate_name,
                second_cate_id,
                second_cate_name,
                discount,
                exclude_cate,
                shop_id,
                shop_name,
                shop_province_id,
                shop_city_id,
                shop_area_id,
                exclude_shop,
            from_unixtime(unix_timestamp(edit_time),'yyyyMMddHHmmss') as edit_time,
                from_unixtime(unix_timestamp(create_time),'yyyyMMddHHmmss') as create_time,
                    creator,
                editor,
                is_deleted,
                operator_id
     from ods_t_sp_order_snapshot_d
where dayid='$v_date';