create table if not exists ads_salary_base_shop_d (
  shop_id string comment '门店id',
  shop_name string comment '门店名称',
  shop_pro_name string comment '门店省',
  shop_city_name string comment '门店市',
  shop_area_name string comment '门店区',
  shop_pay_status string comment '门店下单状态',
  is_cur_month_new_sign string comment '是否本月B有效门店',

  new_sign_pure_pay_amount decimal(11,2) comment '新开日冻结B净支付金额(计算新开专用)',
  new_sign_pay_day string comment 'B有效新开日期',
  new_sign_service_user_id string comment 'B有效新开人userId',
  new_sign_service_user_name string comment 'B有效新开人',
  min_big_b_pay_day string comment '首次下单B日期',
  max_big_b_date string comment '最近支付B日期',
  cur_month_max_big_g_pure_amount decimal(18,2) comment '本月最大日净支付金额',
  last_month_max_big_g_pure_amount decimal(18,2) comment '上月最大日净支付金额',
  is_bd_top10 string comment '是否销售top10门店',
  cur_month_reach_goal int comment '本月门店B达标线',
  cur_month_big_b_pure_gmv decimal(18,2) comment '本月B净GMV（包含线下退款）',
  cur_month_is_reach string comment '本月是否达标（包含线下退款）',
  cur_month_balance decimal(11,2) comment '本月达标差距',
  last_month_reach_goal int comment '上月达标线',
  last_month_big_b_pure_gmv decimal(18,2) comment '上月B净GMV（包含线下退款）',
  last_month_is_reach string comment '上月是否达标（包含线下退款）',

  cur_month_b_level string comment '本月月B类门店坎级',
  last_month_b_level string comment '上月B类门店坎级',
  cur_month_b_category_count string comment '本月B类下单类目数',
  last_month_b_category_count string comment '上月B类下单类目数',
  cur_month_a_pure_gmv decimal(18,2) comment '本月A类净GMV',
  last_month_a_pure_gmv decimal(18,2) comment '上月A类净GMV',
  cur_month_a_level string comment '本月A类门店坎级',
  last_month_a_level string comment '上月A类门店坎级',

  max_valid_visit_time string comment '历史最近有效拜访时间',
  cur_month_valid_visit_time decimal(11,2) comment '本月有效拜访在店时长',
  cur_month_valid_visit_count string comment '本月有效拜访次数',

  bd_feature_names string comment '门店库内销售职能',
  bd_user_ids string comment '门店库内销售人员id',
  bd_user_names string comment '门店库内销售人员',
  bd_department_ids string comment '门店库内销售人员组id',
  bd_department_names string comment '门店库内销售人员组',
  op_feature_names string comment '门店库内电销职能',
  op_user_ids string comment '门店库内电销人员id',
  op_user_names string comment '门店库内电销人员',
  op_department_ids string comment '门店库内电销人员组id',
  op_department_names string comment '门店库内电销人员组',
  store_type_name string comment '门店类型',
  approve_status_name string comment '门店认证状态',
  not_new_sign_reason string comment '非B有效新开原因',
  shop_pro_id int comment '门店省id',
  shop_city_id int comment '门店市id',
  shop_area_id int comment '门店区id',
  update_time string comment '更新时间',
  max_last_b_date string  comment '本月之前的最近冻结B类下单日期',
	all_beforel_ast_month_b_gmv decimal(18,2) comment '本月之前的历史冻结B类净GMV(含线下退款)',
	is_silent string comment '静默/无效门店',
	is_silent_type string comment '静默无效激活状态',
	cur_month_min_b_pay_day string comment '静默无效激活日期',
	is_silent_service_user_id string comment '静默无效激活人user_id',
	is_silent_service_user_name string  comment '静默无效激活人',
	is_brand_shop string comment '可否多品进店',
	is_brand_shop_type string comment '多品进店状态',
	brand_name string comment '多品进店品牌',
	is_brand_pay_day string comment '多品进店日期',
	is_brand_service_user_id string comment '多品进店激活人',
	is_brand_service_user_name  string comment '多品进店激活人名',
	area_manager_dep_name  string comment '大区名',
	bd_manager_dep_name  string comment '主管区域名',
	shop_address_name  string comment '门店街道名',
	is_shop_status string comment '是否冻结',
	today_b_gmv decimal(18,2) comment '今日B类净GMV(库内,包含服务商)',
	today_exclude_sp_b_gmv decimal(18,2) COMMENT '今日B类净GMV(剔除服务商)',
  pre_month_exclude_sp_b_gmv decimal(18,2) COMMENT '上月B类净GMV(剔除服务商)',
  cur_month_exclude_sp_b_gmv decimal(18,2) COMMENT '本月B类净GMV(剔除服务商)'
)
comment '门店主题域集市表'
partitioned by (dayid string)
row format delimited fields terminated by '\001'
stored as orc;