select shop_id,
       shop_name,
       shop_type,
       store_type,
       shop_linker,
       shop_phone,
       shop_fax,
       area_id,
       shop_adress,
       shop_tenpay,
       shop_bus_lic,
       shop_org_cord,
       shop_remark1,
       shop_remark2,
       from_unixtime(unix_timestamp(creat_time), 'yyyyMMddHHmmss')  as creat_time,
       from_unixtime(unix_timestamp(edit_time), 'yyyyMMddHHmmss')   as edit_time,
       creat_user,
       edit_user,
       inuse,
       shop_num,
       shop_alipay_name,
       shop_alipay,
       identitycard,
       shop_company,
       shop_bank,
       shop_banknum,
       shop_addressee,
       shop_zipcode,
       record_shop,
       record_num,
       record_address,
       from_unixtime(unix_timestamp(record_time), 'yyyyMMddHHmmss') as record_time,
       user_id,
       parent_id,
       provincearea_id,
       cityarea_id,
       shop_status,
       vip_server,
       after_server,
       vip_maturity,
       after_maturity,
       prefecture,
       wechat_share,
       level,
       shop_face_pic,
       shop_notice,
       qr_code_path,
       shop_money,
       is_restrict,
       shop_qrcode,
       collect_type,
       is_agree,
       from_unixtime(unix_timestamp(agree_time), 'yyyyMMddHHmmss')  as agree_time,
       agree_user,
       qr_code_pic_path,
       chain_type,
       sharing_percent,
       nick_name,
       shop_grade,
       is_open_operation,
       tp_delivery_add_type,
       is_show_timelimit,
       shop_group,
       is_hipac_certification,
       shop_decoration,
       yiji_user_id,
       distributor_percent,
       shop_ee_percent,
       map_address,
       latitude,
       longitude,
       approve_status,
       apply_type,
       from_unixtime(unix_timestamp(open_time), 'yyyyMMddHHmmss')   as open_time,
       opener,
       bu_id,
       case when address_id is null or address_id = '' then '其他' else address_id end,
       sub_store_type
from ods_t_shop_d
where dayid='$datadate'
  and shop_status in (1, 2, 3, 4, 5)
  and inuse=1
  and provincearea_id is not null
  and provincearea_id!=''
  and dc_id=0;