create table if not exists dw_salary_gmv_rule_public_d
(
update_time                        string          comment '更新时间',
update_month                       string          comment '执行月份',
plan_type                          string          comment '明细类型',
plan_month                         string          comment '方案月份',
plan_pay_time                      string          comment '方案时间',
plan_name                          string          comment '方案名称',
plan_group_id                      string          comment ' 归属业务组id',
plan_group_name                    string          comment ' 归属业务组',
business_unit                      string          comment '业务域',
category_id_first                  bigint          comment '商品一级类目id',
category_id_second                 bigint          comment '商品二级类目id',
category_id_first_name             string          comment '商品一级类目',
category_id_second_name            string          comment '商品二级类目',
brand_id                           bigint          comment '商品品牌id',
brand_name                         string          comment '商品品牌',
item_id                            bigint          comment '商品ID',
item_name                          string          comment '商品名称',
item_style                         tinyint         comment 'AB类型',
item_style_name                    string          comment 'AB类型名称',
is_sp_shop                         string          comment '是否服务商订单',
is_bigbd_shop                      string          comment '是否大BD门店',
is_spec_order                      string          comment '是否特殊订单',
shop_id                            string          comment '门店ID',
shop_name                          string          comment '门店名称',
store_type                         string          comment '门店类型',
store_type_name                    string          comment '门店类型名称',
war_zone_id                        string          comment '战区经理ID',
war_zone_name                      string          comment '战区经理',
war_zone_dep_id                    string          comment '战区ID',
war_zone_dep_name                  string          comment '战区',
area_manager_id                    string          comment '大区经理id',
area_manager_name                  string          comment '大区经理',
area_manager_dep_id                string          comment '大区区域ID',
area_manager_dep_name              string          comment '大区',
bd_manager_id                      string          comment '主管id',
bd_manager_name                    string          comment '主管',
bd_manager_dep_id                  string          comment '主管区域ID',
bd_manager_dep_name                string          comment '区域',
sp_id                              bigint          comment '服务商ID',
sp_name                            string          comment '服务商名',
sp_operator_name                   string          comment '服务商经理名',
service_user_names_freezed         string          comment '冻结销售人员姓名',
service_feature_names_freezed      string          comment '冻结销售人员职能',
service_job_names_freezed          string          comment '冻结销售人员角色',
service_department_names_freezed   string          comment '冻结销售人员部门',
service_info_freezed               string   ,
service_info                       string   ,
gmv_less_refund                    decimal(18,2)   comment '实货gmv-退款',
gmv                                decimal(18,2)   comment '实货gmv',
pay_amount                         decimal(18,2)   comment '实货支付金额',
pay_amount_less_refund             decimal(18,2)   comment '实货支付金额-退款',
refund_actual_amount               decimal(18,2)   comment '实货退款',
refund_retreat_amount              decimal(18,2)   comment '实货清退金额',
grant_object_type                  string          comment '发放对象类型',
grant_object_user_id               string          comment '发放对象ID',
grant_object_user_name             string          comment '发放对象名称',
grant_object_user_dep_id           string          comment '发放对象部门ID',
grant_object_user_dep_name         string          comment '发放对象部门',
leave_time                         string          comment '发放对象离职时间',
is_leave                           string          comment '发放对象是否离职',
sts_target_name                    string          comment '统计指标名称',
sts_target                         decimal(18,2)   comment '统计指标数值',
pay_day                            string          comment '支付日期',
planno                             int             comment '方案编号'
)comment 'gmv规则通用模板明细表'
partitioned by (dayid string,pltype string)
stored as orc;

CREATE TABLE if not exists ytdw.dw_salary_sign_item_rule_public_d(
  update_time                             string        COMMENT '更新时间',
  update_month                            string        COMMENT '执行月份',
  plan_type                               string        COMMENT '明细类型',
  plan_month                              string        COMMENT '方案月份',
  plan_pay_time                           string        COMMENT '方案时间',
  plan_name                               string        COMMENT '方案名称',
  plan_group_id                           string        COMMENT ' 归属业务组id',
  plan_group_name                         string        COMMENT ' 归属业务组',
  item_id                                 bigint        COMMENT '商品ID',
  item_name                               string        COMMENT '商品名称',
  brand_id                                bigint        COMMENT '商品品牌id',
  brand_name                              string        COMMENT '商品品牌',
  item_style                              tinyint       COMMENT 'AB类型',
  item_style_name                         string        COMMENT 'AB类型名称',
  shop_id                                 string        COMMENT '门店ID',
  shop_name                               string        COMMENT '门店名称',
  store_type                              string        COMMENT '门店类型',
  store_type_name                         string        COMMENT '门店类型名称',
  war_zone_id                             string        COMMENT '战区经理ID',
  war_zone_name                           string        COMMENT '战区经理',
  war_zone_dep_id                         string        COMMENT '战区ID',
  war_zone_dep_name                       string        COMMENT '战区',
  area_manager_id                         string        COMMENT '大区经理id',
  area_manager_name                       string        COMMENT '大区经理',
  area_manager_dep_id                     string        COMMENT '大区区域ID',
  area_manager_dep_name                   string        COMMENT '大区',
  bd_manager_id                           string        COMMENT '主管id',
  bd_manager_name                         string        COMMENT '主管',
  bd_manager_dep_id                       string        COMMENT '主管区域ID',
  bd_manager_dep_name                     string        COMMENT '区域',
  service_user_id_freezed                 string        COMMENT '冻结销售人员ID',
  service_department_id_freezed           string        COMMENT '冻结销售人员部门ID',
  service_user_name_freezed               string        COMMENT '冻结销售人员姓名',
  service_feature_name_freezed            string        COMMENT '冻结销售人员职能',
  service_job_name_freezed                string        COMMENT '冻结销售人员角色',
  service_department_name_freezed         string        COMMENT '冻结销售人员部门',
  new_sign_time                           string        COMMENT '新签时间',
  new_sign_day                            string        COMMENT '新签日期',
  new_sign_rn                             string        COMMENT '新签时间排名达成',
  shop_item_sign_day                      string        COMMENT '门店商品新签时间',
  gmv_less_refund                         decimal(18,2) COMMENT '实货gmv-退款',
  gmv                                     decimal(18,2) COMMENT '实货gmv',
  pay_amount                              decimal(18,2) COMMENT '实货支付金额',
  pay_amount_less_refund                  decimal(18,2) COMMENT '实货支付金额-退款',
  refund_actual_amount                    decimal(18,2) COMMENT '实货退款',
  refund_retreat_amount                   decimal(18,2) COMMENT '实货清退金额',
  new_sign_line                           decimal(18,2) COMMENT '新签门槛线',
  is_over_sign_line                       string        COMMENT '是否满足新签门槛',
  is_first_sign                           string        COMMENT '是否首次达成',
  is_succ_sign                            string        COMMENT '否新签成功',
  grant_object_type                       string        COMMENT '发放对象类型',
  grant_object_user_id                    string        COMMENT '发放对象ID',
  grant_object_user_name                  string        COMMENT '发放对象名称',
  grant_object_user_dep_id                string        COMMENT '发放对象部门ID',
  grant_object_user_dep_name              string        COMMENT '发放对象部门',
  leave_time                              string        COMMENT '发放对象离职时间',
  is_leave                                string        COMMENT '发放对象是否离职',
  sts_target_name                         string        COMMENT '统计指标名称',
  planno                                  int           COMMENT '方案编号'
  )
COMMENT '新签商品规则通用模板明细表'
PARTITIONED BY (dayid string, pltype string)
stored as orc;

CREATE TABLE if not exists ytdw.dw_salary_sign_brand_rule_public_d(
update_time                     string        COMMENT '更新时间',
update_month                    string        COMMENT '执行月份',
plan_type                       string        COMMENT '明细类型',
plan_month                      string        COMMENT '方案月份',
plan_pay_time                   string        COMMENT '方案时间',
plan_name                       string        COMMENT '方案名称',
plan_group_id                   string        COMMENT ' 归属业务组id',
plan_group_name                 string        COMMENT ' 归属业务组',
brand_id                        bigint        COMMENT '商品品牌id',
brand_name                      string        COMMENT '商品品牌',
item_style                      tinyint       COMMENT 'AB类型',
item_style_name                 string        COMMENT 'AB类型名称',
shop_id                         string        COMMENT '门店ID',
shop_name                       string        COMMENT '门店名称',
store_type                      string        COMMENT '门店类型',
store_type_name                 string        COMMENT '门店类型名称',
war_zone_id                     string        COMMENT '战区经理ID',
war_zone_name                   string        COMMENT '战区经理',
war_zone_dep_id                 string        COMMENT '战区ID',
war_zone_dep_name               string        COMMENT '战区',
area_manager_id                 string        COMMENT '大区经理id',
area_manager_name               string        COMMENT '大区经理',
area_manager_dep_id             string        COMMENT '大区区域ID',
area_manager_dep_name           string        COMMENT '大区',
bd_manager_id                   string        COMMENT '主管id',
bd_manager_name                 string        COMMENT '主管',
bd_manager_dep_id               string        COMMENT '主管区域ID',
bd_manager_dep_name             string        COMMENT '区域',
service_user_id_freezed         string        COMMENT '冻结销售人员ID',
service_department_id_freezed   string        COMMENT '冻结销售人员部门ID',
service_user_name_freezed       string        COMMENT '冻结销售人员姓名',
service_feature_name_freezed    string        COMMENT '冻结销售人员职能',
service_job_name_freezed        string        COMMENT '冻结销售人员角色',
service_department_name_freezed string        COMMENT '冻结销售人员部门',
new_sign_time                   string        COMMENT '新签时间',
new_sign_day                    string        COMMENT '新签日期',
new_sign_rn                     string        COMMENT '新签时间排名达成',
shop_brand_sign_day             string        COMMENT '门店品牌新签时间',
gmv_less_refund                 decimal(18,2) COMMENT '实货gmv-退款',
gmv                             decimal(18,2) COMMENT '实货gmv',
pay_amount                      decimal(18,2) COMMENT '实货支付金额',
pay_amount_less_refund          decimal(18,2) COMMENT '实货支付金额-退款',
refund_actual_amount            decimal(18,2) COMMENT '实货退款',
refund_retreat_amount           decimal(18,2) COMMENT '实货清退金额',
new_sign_line                   decimal(18,2) COMMENT '新签门槛线',
is_over_sign_line               string        COMMENT '是否满足新签门槛',
is_first_sign                   string        COMMENT '是否首次达成',
is_succ_sign                    string        COMMENT '否新签成功',
grant_object_type               string        COMMENT '发放对象类型',
grant_object_user_id            string        COMMENT '发放对象ID',
grant_object_user_name          string        COMMENT '发放对象名称',
grant_object_user_dep_id        string        COMMENT '发放对象部门ID',
grant_object_user_dep_name      string        COMMENT '发放对象部门',
leave_time                      string        COMMENT '发放对象离职时间',
is_leave                        string        COMMENT '发放对象是否离职',
sts_target_name                 string        COMMENT '统计指标名称',
planno                          int           COMMENT '方案编号'
)
COMMENT '新签品牌规则通用模板明细表'
PARTITIONED BY (dayid string,pltype string)
stored as orc;

CREATE TABLE if not exists ytdw.dw_salary_forward_plan_sum_d(
  update_time                string        COMMENT '更新时间',
  update_month               string        COMMENT '执行月份',
  plan_month                 string        COMMENT '方案月份',
  plan_pay_time              string        COMMENT '方案时间',
  plan_no                    int           COMMENT '方案编号',
  plan_name                  string        COMMENT '方案名称',
  plan_group_id              string        COMMENT ' 归属业务组id',
  plan_group_name            string        COMMENT ' 归属业务组',
  grant_object_type          string        COMMENT '发放对象类型',
  grant_object_user_id       string        COMMENT '发放对象ID',
  grant_object_user_name     string        COMMENT '发放对象名称',
  grant_object_user_dep_id   string        COMMENT '发放对象部门ID',
  grant_object_user_dep_name string        COMMENT '发放对象部门',
  leave_time                 string        COMMENT '发放对象离职时间',
  sts_target_name            string        COMMENT '统计指标名称',
  sts_target                 decimal(18,2) COMMENT '统计指标数值',
  real_coefficient_goal_rate string        COMMENT '发放对象的当月系数',
  commission_cap             string        COMMENT '提成上限',
  commission_plan_type       string        COMMENT '提成方案类型',
  commission_reward_type     string        COMMENT '提成奖品类型 金额/实物',
  commission_reward          string        COMMENT '提成奖品',
  planno                     int           COMMENT '方案编号'
)
COMMENT '正向方案汇总表'
PARTITIONED BY (
  dayid string,bounty_rule_type int)
stored as orc;

CREATE TABLE if not exists ytdw.dw_salary_backward_plan_sum_mid_d(
  update_time                string        COMMENT '更新时间',
  update_month               string        COMMENT '执行月份',
  plan_month                 string        COMMENT '方案月份',
  plan_pay_time              string        COMMENT '方案时间',
  plan_no                    int           COMMENT '方案编号',
  plan_name                  string        COMMENT '方案名称',
  plan_group_id              string        COMMENT ' 归属业务组id',
  plan_group_name            string        COMMENT ' 归属业务组',
  grant_object_type          string        COMMENT '发放对象类型',
  grant_object_user_id       string        COMMENT '发放对象ID',
  grant_object_user_name     string        COMMENT '发放对象名称',
  grant_object_user_dep_id   string        COMMENT '发放对象部门ID',
  grant_object_user_dep_name string        COMMENT '发放对象部门',
  leave_time                 string        COMMENT '发放对象离职时间',
  sts_target_name            string        COMMENT '统计指标名称',
  sts_target                 decimal(18,2) COMMENT '统计指标数值',
  real_coefficient_goal_rate string        COMMENT '发放对象的当月系数',
  commission_cap             string        COMMENT '提成上限',
  commission_plan_type       string        COMMENT '提成方案类型',
  commission_reward_type     string        COMMENT '提成奖品类型 金额/实物',
  commission_reward          string        COMMENT '提成奖品',
  planno                     int           COMMENT '方案编号'
)
COMMENT '历史方案汇总中间表'
PARTITIONED BY (dayid string,bounty_rule_type int)
stored as orc;

CREATE TABLE if not exists ytdw.dw_salary_backward_plan_sum_d(
  update_time                string        COMMENT '更新时间',
  update_month               string        COMMENT '执行月份',
  plan_month                 string        COMMENT '方案月份',
  plan_pay_time              string        COMMENT '方案时间',
  plan_no                    int           COMMENT '方案编号',
  plan_name                  string        COMMENT '方案名称',
  plan_group_id              string        COMMENT ' 归属业务组id',
  plan_group_name            string        COMMENT ' 归属业务组',
  grant_object_type          string        COMMENT '发放对象类型',
  grant_object_user_id       string        COMMENT '发放对象ID',
  grant_object_user_name     string        COMMENT '发放对象名称',
  grant_object_user_dep_id   string        COMMENT '发放对象部门ID',
  grant_object_user_dep_name string        COMMENT '发放对象部门',
  leave_time                 string        COMMENT '发放对象离职时间',
  sts_target_name            string        COMMENT '统计指标名称',
  sts_target                 decimal(18,2) COMMENT '统计指标数值',
  real_coefficient_goal_rate string        COMMENT '发放对象的当月系数',
  commission_cap             string        COMMENT '提成上限',
  commission_plan_type       string        COMMENT '提成方案类型',
  commission_reward_type     string        COMMENT '提成奖品类型 金额/实物',
  cur_commission_reward      string        COMMENT '当前统计的提成奖品',
  pre_commission_reward      string        COMMENT '上一月份的提成奖品',
  commission_reward_change   string        COMMENT '提成奖品变化',
  planno                     int           COMMENT '方案编号'
)
COMMENT '逆向方案汇总表'
PARTITIONED BY (dayid string)
stored as orc;