CREATE TABLE `bounty_plan` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '方案编号',
  `name` varchar(60) COLLATE utf8mb4_bin NOT NULL COMMENT '方案名称',
  `status` tinyint(4) DEFAULT NULL COMMENT '方案状态：1 正常，9 已废弃',
  `owner_type` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '方案归属类型：1业务组、2销售部',
  `subject_id` bigint(20) unsigned DEFAULT NULL,
  `subject_name` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'P0项目名称',
  `remark` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '方案备注',
  `biz_group_id` bigint(11) DEFAULT NULL COMMENT '业务组ID',
  `biz_group_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务组名称',
  `month` char(7) COLLATE utf8mb4_bin NOT NULL COMMENT '方案月份，格式：2019-12',
  `bounty_payout_object_id` int(11) NOT NULL COMMENT '发放对象ID',
  `bounty_rule_type` tinyint(4) NOT NULL COMMENT '模板规则，枚举：1为存量GMV',
  `bounty_rule_type_id` int(10) unsigned DEFAULT NULL COMMENT '模板规则枚举ID',
  `bounty_indicator_id` int(11) NOT NULL COMMENT '统计指标ID',
  `filter_config_json` text COLLATE utf8mb4_bin NOT NULL COMMENT '过滤条件',
  `payout_rule_type` tinyint(4) NOT NULL COMMENT '提成类型，枚举：1返现、2返点、3返物',
  `payout_config_json` text COLLATE utf8mb4_bin NOT NULL COMMENT '提成系数及规则',
  `coefficient_config_json` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '提成系数及规则',
  `payout_upper_limit` decimal(15,4) DEFAULT NULL COMMENT '提成上限',
  `job_status` tinyint(2) DEFAULT NULL COMMENT '任务处理状态：1 处理中，2 成功，3 失败',
  `last_edit_time` datetime DEFAULT NULL COMMENT '最后修改时间',
  `creator` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人ID',
  `editor` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_no` (`no`),
  KEY `idx_month` (`month`),
  KEY `idx_creator` (`creator`)
) ENGINE=InnoDB AUTO_INCREMENT=3923 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin