select
id,
trade_id,
trade_no,
parent_trade_id,
out_trade_id,
shop_id,
supply_id,
parent_shop_id,
user_id,
open_id,
from_unixtime(unix_timestamp(third_order_time),'yyyyMMddHHmmss') as third_order_time,
trade_type,
trade_source,
trade_status,
pay_amount,
logistic_amount,
logistic_pay_type,
trade_remark,
shop_remark,
clerk_name,
clerk_phone,
address_id,
area_id,
city_area_id,
province_area_id,
delivery_name,
delivery_phone,
detail_address,
customer_id,
customer_id_card,
customer_name,
customer_phone,
tags,
is_cart,
attribute,
promotion_attr,
has_parent,
hide,
from_unixtime(unix_timestamp(pay_time),'yyyyMMddHHmmss') as pay_time,
from_unixtime(unix_timestamp(end_time),'yyyyMMddHHmmss') as end_time,
is_deleted,
creator,
editor,
from_unixtime(unix_timestamp(create_time),'yyyyMMddHHmmss') as create_time,
from_unixtime(unix_timestamp(edit_time),'yyyyMMddHHmmss') as edit_time,
ytdw.getValueFromJson(promotion_attr,6,'bizId') as coupon_owner_id,
nvl(ytdw.getValueFromJson(promotion_attr,10,'bizAmount'),0)+nvl(ytdw.getValueFromJson(promotion_attr,6,'bizAmount'),0) as coupon_amount,
nvl(ytdw.getValueFromJson(promotion_attr,7,'bizAmount'),0) as hi_amount,
ytdw.getValueFromKVString(attribute,'B') as order_notice,
nvl(ytdw.getValueFromJson(promotion_attr,6,'bizAmount'),0) as coupon_amount_platform,
nvl(ytdw.getValueFromJson(promotion_attr,10,'bizAmount'),0) as coupon_amount_store,
ytdw.getValueFromJson(promotion_attr,10,'bizId') as coupon_owner_id_store,
bu_id,
nvl(ytdw.getValueFromKVString(attribute,'saleDcId'),-1) as sale_dc_id,
trade_from
from ods_pt_trade_shop_d
where dayid='$datadate' and regexp_extract(attribute,'(off:)([0-9]*)(\;?)',2) != '1' and item_dc_id=0;