select
id,
order_id,
order_no,
trade_id,
shop_id,
supply_id,
item_id,
item_name,
item_count,
origin_single_item_amount,
pay_amount,
tax_amount,
item_actual_amount,
customer_amount,
sharing_amount,
logistic_type,
logistic_pay_type,
logistic_amount,
attribute,
spu_feature,
spec,
spec_desc,
item_picture,
promotion_attr,
order_status,
refund_status,
biz_id,
biz_type,
out_attr,
bonded_area_id,
tags,
from_unixtime(unix_timestamp(accept_time),'yyyyMMddHHmmss') as accept_time,
from_unixtime(unix_timestamp(pay_time),'yyyyMMddHHmmss') as pay_time,
from_unixtime(unix_timestamp(stock_out_time),'yyyyMMddHHmmss') as stock_out_time,
from_unixtime(unix_timestamp(delivery_time),'yyyyMMddHHmmss') as delivery_time,
from_unixtime(unix_timestamp(end_time),'yyyyMMddHHmmss') as end_time,
is_deleted,
creator,
editor,
from_unixtime(unix_timestamp(create_time),'yyyyMMddHHmmss') as create_time,
from_unixtime(unix_timestamp(edit_time),'yyyyMMddHHmmss') as edit_time,
ytdw.getValueFromJson(promotion_attr,6,'bizId') as coupon_owner_id,
nvl(ytdw.getValueFromJson(promotion_attr,10,'bizAmount'),0)+nvl(ytdw.getValueFromJson(promotion_attr,6,'bizAmount'),0) as coupon_amount,
nvl(ytdw.getValueFromJson(promotion_attr,7,'bizAmount'),0) as hi_amount,
ytdw.getValueFromKVString(attribute,'C') as batch_id,
nvl(ytdw.getValueFromKVString(attribute,'batchVersion'),0) as batch_version,
ytdw.getValueFromKVString(attribute,'D') as batch_spec_price,
nvl(ytdw.getValueFromKVString(attribute,'i_v'),1) as item_snapshot_version,
nvl(ytdw.getValueFromJson(promotion_attr,6,'bizAmount'),0) as coupon_amount_platform,
nvl(ytdw.getValueFromJson(promotion_attr,10,'bizAmount'),0) as coupon_amount_store,
ytdw.getValueFromJson(promotion_attr,10,'bizId') as coupon_owner_id_store,
bu_id,
nvl(ytdw.getValueFromJson(promotion_attr,12,'bizAmount'),0) as pickup_card_amount,
nvl(ytdw.getValueFromKVString(attribute,'saleDcId'),-1) as sale_dc_id,
sku_id
,item_dc_id
from ods_pt_order_shop_d
where dayid='$v_date'
and regexp_extract(attribute,'(off:)([0-9]*)(\;?)',2) <> '1' --原因你懂的
and order_id<>36133857 --脏数据，订单金额过大
;